"""add notification fields to budget

Revision ID: 17716ed2fa20
Revises: 8605d2123535
Create Date: 2025-03-19 10:57:27.523152

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "17716ed2fa20"
down_revision = "8605d2123535"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "warning_notification_sent",
                sa.Boolean(),
                server_default="false",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "exceeded_notification_sent",
                sa.Boolean(),
                server_default="false",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.drop_column("exceeded_notification_sent")
        batch_op.drop_column("warning_notification_sent")

    # ### end Alembic commands ###
