"""fields

Revision ID: 8605d2123535
Revises: 74d96b3595a6
Create Date: 2025-03-18 16:41:29.136258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8605d2123535'
down_revision = '74d96b3595a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('CREDIT', 'DEBIT', name='transactiontype'), nullable=False))
        batch_op.add_column(sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='frequency'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.drop_column('frequency')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
